# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: destroyed-symlinks
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: mixed-line-ending

- repo: local
  hooks:
  - id: markdownlint
    name: markdownlint
    language: docker_image # for some reason docker image doesn't build in this step
    entry: precommit-markdown markdownlint  # add --fix for autoformat
    files: \.md$
