# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: destroyed-symlinks
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: mixed-line-ending

#- repo: https://github.com/igorshubovych/markdownlint-cli
#  rev: v0.28.1
#  hooks:
#  - id: markdownlint
