baseURL = "http://timurb.ru"
languageCode = "ru-ru"
title = "Об DevOps и архитектуру"
theme = "ink"

uglyurls = true
relativeURLs = true


[markup]
  defaultMarkdownHandler = "goldmark"


[permalinks]
  post = ":filename"
