baseURL = "http://timurb.ru/"
theme = "ink"

relativeURLs = true

googleAnalytics = "G-XHRMHV11BE"
sectionPagesMenu = "main"

languageCode = "ru-ru"
title = "Об DevOps и архитектуру"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  post = ":filename"


[menu]   
  [[menu.main]]
    identifier = "about"
    name = "Об авторе"
    url = "/about"
    weight = -110

[params]
customCSS = "css/custom.css"
