baseURL = "https://timurb.ru/"
theme = "ink"

relativeURLs = true

googleAnalytics = "G-XHRMHV11BE"

languageCode = "ru-ru"
title = "Об DevOps и архитектуру"

pluralizelisttitles = "false"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  post = ":filename"


[menu]   
  [[menu.about]]
    identifier = "about"
    name = "Об авторе"
    url = "/about"
    weight = -110

  [[menu.kb]]
    identifier = "kb"
    name = "Оглавление"
    url = "/kb"


[params]
customCSS = "css/custom.css"
mainSections = ["blog", "kb"]
