baseURL = "http://timurb.ru/"
languageCode = "ru-ru"
title = "Об DevOps и архитектуру"
theme = "ink"

uglyurls = true
relativeURLs = true

googleAnalytics = "G-XHRMHV11BE"
sectionPagesMenu = "main"

[markup]
  defaultMarkdownHandler = "goldmark"


[permalinks]
  post = ":filename"

[menu]

  [[menu.main]]
  identifier = "about"
  name = "Об авторе"
  url = "/about.html"
  weight = -110
