baseURL = "http://timurb.ru/"
languageCode = "ru-ru"
title = "Об DevOps и архитектуру"
theme = "ink"

uglyurls = true
relativeURLs = true

googleAnalytics = "UA-43321747-4"

[markup]
  defaultMarkdownHandler = "goldmark"


[permalinks]
  post = ":filename"
